name: GitHub Readme YouTube Cards
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCFzOomVm2_kFnMEk_Hr19ZA
          comment_tag_name: YOUTUBE-CARDS-DC
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
          show_duration: true
          max_videos: 3
